<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="ea793ea7-c773-45a9-9df3-be0cf5e3d8db" name="spf@WKSPF4 2011-05-18 01:13:39" runUser="ASCORP\spf" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="9c902be1-ba22-4d4e-825f-91cd920b426b">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="spf_WKSPF4 2011-05-18 01_13_39">
      <DeploymentItem filename="C:\SPF\prompt11\uc01\repos\PROMPT11-01-VMEssentials.sandrapatfer\Sessao 4\Sessao4\Binding\bin\Debug\Binding.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2011-05-18T01:13:39.0748380+01:00" queuing="2011-05-18T01:13:39.0838385+01:00" start="2011-05-18T01:13:39.0994385+01:00" finish="2011-05-18T01:13:39.3646390+01:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="bind2_when_member_is_required_throws_exception" storage="c:\spf\prompt11\uc01\repos\prompt11-01-vmessentials.sandrapatfer\sessao 4\sessao4\binding.tests2\bin\debug\binding.tests2.dll" id="f11e6c16-2163-7acc-ecbe-3f27e3d20827">
      <Execution id="c3c3c6ee-c43f-4d67-a604-58e89f5ff7f7" />
      <TestMethod codeBase="C:/SPF/prompt11/uc01/repos/PROMPT11-01-VMEssentials.sandrapatfer/Sessao 4/Sessao4/Binding.Tests2/bin/Debug/Binding.Tests2.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="Binding.Tests2.BindingTests, Binding.Tests2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="bind2_when_member_is_required_throws_exception" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="f11e6c16-2163-7acc-ecbe-3f27e3d20827" executionId="c3c3c6ee-c43f-4d67-a604-58e89f5ff7f7" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="c3c3c6ee-c43f-4d67-a604-58e89f5ff7f7" testId="f11e6c16-2163-7acc-ecbe-3f27e3d20827" testName="bind2_when_member_is_required_throws_exception" computerName="WKSPF4" duration="00:00:00.0331937" startTime="2011-05-18T01:13:39.0994385+01:00" endTime="2011-05-18T01:13:39.3490390+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="c3c3c6ee-c43f-4d67-a604-58e89f5ff7f7">
      <Output>
        <ErrorInfo>
          <Message>Test method Binding.Tests2.BindingTests.bind2_when_member_is_required_throws_exception did not throw expected exception Binding.InvalidMemberTypeException.</Message>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>